# Generated by Django 6.0.2 on 2026-02-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_question_correct_choice_question_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='content_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='content_markdown',
            field=models.TextField(blank=True),
        ),
    ]
