# Generated by Django 6.0.2 on 2026-02-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_quiz_content_html_quiz_content_markdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='content_html',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='content_markdown',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='pass_mark',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='questions_count',
        ),
        migrations.AddField(
            model_name='choice',
            name='answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='choice',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='content_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='content_markdown',
            field=models.TextField(blank=True),
        ),
    ]
