# Generated by Django 6.0.2 on 2026-02-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_choice_is_correct_remove_choice_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.CharField(choices=[('A', ''), ('B', ''), ('C', ''), ('D', '')], default='A'),
        ),
    ]
