# Generated by Django 6.0.2 on 2026-02-10 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_question_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='lessonquizattempt',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='lessonquizattempt',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='lessonquizattempt',
            name='user_answers',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_choice',
        ),
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='choice',
            name='label',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='choice',
            name='text',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lessonquizattempt',
            name='answers',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='lessonquizattempt',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessonquizattempt',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='description_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='description_markdown',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='pass_score',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.PositiveIntegerField(default=10, help_text='Time limit in minutes'),
        ),
        migrations.AlterField(
            model_name='lessonquizattempt',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lessonquizattempt',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
