# Generated by Django 6.0.2 on 2026-02-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_question_correct_choice_questionbank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='description_html',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='description_markdown',
        ),
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, default='Quiz instructions/description in rich-text format'),
        ),
    ]
