# Generated by Django 6.0.2 on 2026-02-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_remove_quiz_description_html_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='text',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='label',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice',
            field=models.CharField(default='A', max_length=2),
        ),
    ]
