# Generated by Django 6.0.2 on 2026-02-11 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_rename_text_choice_answer_remove_choice_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherapplication',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.teacher'),
        ),
    ]
