# Generated by Django 6.0.2 on 2026-02-11 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_alter_quiz_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='bank_question',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='content_html',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='content_markdown',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='topic',
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_bank', to='courses.question'),
        ),
    ]
