# Generated by Django 6.0.2 on 2026-02-11 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_remove_question_bank_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonquizattempt',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='lessonquizattempt',
            name='passed',
        ),
        migrations.AddField(
            model_name='lessonquizattempt',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='lessonquizattempt',
            name='questions',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='lessonquizattempt',
            name='user_answers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonquizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.quiz'),
        ),
        migrations.AlterField(
            model_name='lessonquizattempt',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lessonquizattempt',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
