# Generated by Django 6.0.2 on 2026-02-12 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_remove_lessonquizattempt_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='last_scroll_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='progress_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lessonquizattempt',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.quiz'),
        ),
    ]
