# Generated by Django 6.0.2 on 2026-02-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_lessonprogress_last_scroll_position_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonquizattempt',
            old_name='user_answers',
            new_name='answers',
        ),
        migrations.AddField(
            model_name='lessonquizattempt',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
