# Generated by Django 6.0.2 on 2026-02-13 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_lesson_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='video',
            new_name='video_url',
        ),
    ]
