# Generated by Django 6.0.2 on 2026-02-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_remove_lesson_video_url_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videos',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
