# Generated by Django 6.0.2 on 2026-02-13 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_videos_is_free_videos_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
