# Generated by Django 6.0.2 on 2026-02-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_delete_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField(default=0)),
                ('is_free', models.BooleanField(default=False)),
            ],
        ),
    ]
