# Generated by Django 6.0.2 on 2026-02-13 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_videoprop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoProp',
        ),
    ]
