# Generated by Django 6.0.2 on 2026-02-14 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_alter_lesson_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='video',
            name='order',
        ),
    ]
