# Generated by Django 6.0.2 on 2026-02-17 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_aiquizpayment_aiquiz_aiquizquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonquizattempt',
            name='user_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='attempts',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='lessonquizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_quiz_attempt', to=settings.AUTH_USER_MODEL),
        ),
    ]
