# Generated by Django 6.0.2 on 2026-02-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_resource_author_resource_external_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
