# Generated by Django 6.0.2 on 2026-02-18 00:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_alter_resource_uploaded_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resource',
            new_name='PDFResource',
        ),
    ]
