# Generated by Django 6.0.2 on 2026-02-18 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_rename_resource_pdfresource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfresource',
            name='lesson',
        ),
        migrations.AddField(
            model_name='pdfresource',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.course'),
        ),
    ]
