# Generated by Django 6.0.2 on 2026-02-18 22:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0041_alter_lesson_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfresource',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pdfresource',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Set price only if paid resource', max_digits=8),
        ),
        migrations.AlterField(
            model_name='pdfresource',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pdfresource',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='pdfresource',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PDFPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('paid', models.BooleanField(default=False)),
                ('campay_reference', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.pdfresource')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'pdf')},
            },
        ),
    ]
