# Generated by Django 6.0.2 on 2026-02-25 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0047_classroommessage_delete_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroommessage',
            options={'ordering': ['created']},
        ),
        migrations.RenameField(
            model_name='classroommessage',
            old_name='room_id',
            new_name='classroom_id',
        ),
        migrations.RenameField(
            model_name='classroommessage',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='classroommessage',
            name='is_teacher',
        ),
    ]
