# Generated by Django 6.0.2 on 2026-02-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0049_classroom_live_session_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiquiz',
            name='source_payment',
        ),
        migrations.AddField(
            model_name='aiquiz',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aiquiz',
            name='price',
            field=models.PositiveIntegerField(default=250),
        ),
        migrations.DeleteModel(
            name='AIQuizPayment',
        ),
    ]
