# Generated by Django 6.0.2 on 2026-02-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0051_quiz_course_quiz_is_course_quiz_alter_quiz_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='level',
            field=models.CharField(default='O-Level'),
        ),
    ]
