# Generated by Django 6.0.2 on 2026-02-26 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0052_quiz_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_qb', to='courses.course'),
        ),
    ]
