# Generated by Django 6.0.2 on 2026-02-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0053_questionbank_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='level',
            field=models.CharField(choices=[('O-Level', 'O-Level'), ('A-Level', 'A-Level')], default='O-Level'),
        ),
    ]
