# Generated by Django 6.0.2 on 2026-03-01 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0055_question_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.AddField(
            model_name='aiquiz',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_ai_quiz', to='courses.course'),
        ),
        migrations.AddField(
            model_name='question',
            name='contains_diagram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='contains_math',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aiquiz',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_ai_quiz', to='courses.lesson'),
        ),
        migrations.DeleteModel(
            name='AIQuizQuestion',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
