# Generated by Django 6.0.2 on 2026-03-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0056_remove_subscription_user_aiquiz_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='content_markdown',
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_blocks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_html',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
