# Generated by Django 6.0.2 on 2026-03-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0057_remove_lesson_content_markdown_lesson_content_blocks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
