# Generated by Django 6.0.2 on 2026-03-03 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0058_lesson_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='courses.lesson'),
        ),
    ]
