# Generated by Django 6.0.2 on 2026-03-03 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0059_alter_questionbank_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonquizattempt',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='courses.quiz'),
        ),
    ]
