# Generated by Django 6.0.2 on 2026-03-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0060_alter_lessonquizattempt_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonprogress',
            name='last_scroll_position',
            field=models.FloatField(default=0.0),
        ),
    ]
