# Generated by Django 6.0.2 on 2026-03-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0063_alter_teacherapplication_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
