# Generated by Django 6.0.2 on 2026-03-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0068_alter_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='attempt_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
