# Generated by Django 6.0.2 on 2026-03-09 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0070_specialquizevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonquizattempt',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.lesson'),
        ),
        migrations.DeleteModel(
            name='SpecialQuizEvent',
        ),
    ]
