# Generated by Django 6.0.2 on 2026-03-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0071_alter_lessonquizattempt_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_quick_quiz',
            field=models.BooleanField(default=False),
        ),
    ]
