# Generated by Django 6.0.2 on 2026-03-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0072_quiz_is_quick_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonquizattempt',
            name='question_ids',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
